title: Fossified
description: All things free and open source.<br><br>Suggest topics and speakers <a href="https://github.com/fossified/podcast">here</a> and get your RSS feed <a href="https://pod.fossified.com/podcast.rss">here</a>
author: <a href="https://github.com/bagder">Daniel</a>, <a href="https://github.com/hesa">Henrik</a>, <a href="https://github.com/mhagander">Magnus</a> and <a href="https://github.com/e8johan">Johan</a>
email: info@fossified.com
lang: en-us
copyright: "&#x2117; &amp; &#xA9; 2023"
logo: /assets/img/logo.png
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pod.fossified.com" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
