title: Fossified
description: All things free and open source with <a href="https://github.com/bagder">Daniel</a>, <a href="https://github.com/hesa">Henrik</a>, <a href="https://github.com/mhagander">Magnus</a> and <a href="https://github.com/e8johan">Johan</a>.<br><br>Suggest topics and speakers <a href="https://github.com/fossified/podcast">here</a> and get your RSS feed <a href="https://pod.fossified.com/podcast.rss">here</a>
author: Daniel, Henrik, Magnus and Johan
email: info@fossified.com
lang: en-us
copyright: "&#x2117; &amp; &#xA9;" Daniel, Henrik, Magnus and Johan, <a href="https://github.com/fossified/pod.fossified.com/blob/master/LICENSE">LICENSE</a>.
contributors: the site is based on the work of Martin Ogn and <a href="https://www.oscillator.se/">Staffan Melin</a>.
logo: /assets/img/fossified-1024x268.png
logo-big: /assets/img/fossified-3000x784.png
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://pod.fossified.com" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
